package com.example.creditcardapp.di

import android.content.Context
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteDatabase
import com.example.creditcardapp.BuildConfig
import com.example.creditcardapp.data.local.AppDatabase
import com.example.creditcardapp.data.local.CreditCardDao
import com.example.creditcardapp.data.local.DatabaseKeyStore
import com.example.creditcardapp.data.local.MIGRATION_4_5
import com.example.creditcardapp.data.local.RewardBalanceDao
import com.example.creditcardapp.data.local.RotatingCategoryDao
import com.example.creditcardapp.data.local.TransactionDao
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import net.sqlcipher.database.SQLiteDatabase
import net.sqlcipher.database.SupportFactory
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
object DatabaseModule {

    @Provides
    @Singleton
    fun provideDatabaseKeyStore(@ApplicationContext context: Context): DatabaseKeyStore =
        DatabaseKeyStore(context)

    @Provides
    @Singleton
    fun provideDatabase(
        @ApplicationContext context: Context,
        keyStore: DatabaseKeyStore,
    ): AppDatabase {
        // Load SQLCipher's native libraries before any DB call.
        SQLiteDatabase.loadLibs(context)

        // If we've never written a passphrase, any database file on disk is a
        // legacy (unencrypted) one from a previous build. Delete it so SQLCipher
        // doesn't fail to open it with the new key. fallbackToDestructiveMigration
        // handles schema mismatches but not the encrypted/unencrypted boundary.
        if (!keyStore.hasKey()) {
            context.deleteDatabase(AppDatabase.DB_NAME)
        }
        val passphrase = keyStore.getOrCreatePassphrase()
        val factory = SupportFactory(passphrase)

        val builder = Room.databaseBuilder(context, AppDatabase::class.java, AppDatabase.DB_NAME)
            .openHelperFactory(factory)
            // Explicit migrations preserve user data across upgrades. Fall back to
            // destructive wipe only when no migration path is available (e.g. unknown
            // version coming from a much older install) or on downgrade.
            .addMigrations(MIGRATION_4_5)
            .fallbackToDestructiveMigration()
            .fallbackToDestructiveMigrationOnDowngrade()
        if (BuildConfig.DEBUG) builder.addCallback(DebugSeed)
        return builder.build()
    }

    @Provides
    fun provideCreditCardDao(db: AppDatabase): CreditCardDao = db.creditCardDao()

    @Provides
    fun provideTransactionDao(db: AppDatabase): TransactionDao = db.transactionDao()

    @Provides
    fun provideRewardBalanceDao(db: AppDatabase): RewardBalanceDao = db.rewardBalanceDao()

    @Provides
    fun provideRotatingCategoryDao(db: AppDatabase): RotatingCategoryDao = db.rotatingCategoryDao()

    private object DebugSeed : RoomDatabase.Callback() {
        override fun onCreate(db: SupportSQLiteDatabase) {
            val now = System.currentTimeMillis()
            val sql = """
                INSERT INTO credit_cards
                  (cardholderName, last4, brand, expiryMonth, expiryYear,
                   balance, creditLimit, nickname, updatedAt, rewardsJson,
                   annualFee, pointValueCents,
                   signupBonusRequiredSpend, signupBonusEarnedSpend,
                   signupBonusValue, signupBonusDeadline)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """.trimIndent()
            // Day-30 from now in epoch ms — used to seed a still-active signup bonus.
            val plus60d = now + 60L * 24 * 60 * 60 * 1000

            // Sapphire-style: dining + travel, $95 AF, UR points (1.5¢/pt with travel)
            db.execSQL(sql, arrayOf(
                "", "4242", "Visa", 12, 2028, 1240.55, 8000.0, "Sapphire", now,
                """{"DINING":3.0,"TRAVEL":2.0,"ENTERTAINMENT":2.0,"OTHER":1.0}""",
                95.0, 1.5, 4000.0, 1240.55, 900.0, plus60d
            ))
            // Cash Preferred-style: groceries + gas, $0 AF, cash (1¢/pt)
            db.execSQL(sql, arrayOf(
                "", "8810", "Mastercard", 7, 2027, 320.10, 5000.0, "Cash Preferred", now,
                """{"GROCERIES":6.0,"GAS":3.0,"OTHER":1.0}""",
                0.0, 1.0, 0.0, 0.0, 0.0, null
            ))
            // Platinum-style: travel-heavy, $695 AF, MR (1.5¢/pt)
            db.execSQL(sql, arrayOf(
                "", "1009", "Amex", 3, 2029, 4275.00, 12000.0, "Platinum", now,
                """{"TRAVEL":5.0,"DINING":4.0,"SHOPPING":2.0,"OTHER":1.0}""",
                695.0, 1.5, 8000.0, 4275.00, 1500.0, plus60d
            ))

            // Seed reward-program balances for the Sapphire & Platinum (their cardId
            // = autoGenerated 1 and 3 respectively, in insertion order).
            val balSql = """
                INSERT INTO reward_balances
                  (cardId, programName, points, valuePerPointCents, updatedAt)
                VALUES (?, ?, ?, ?, ?)
            """.trimIndent()
            db.execSQL(balSql, arrayOf(1L, "Chase Ultimate Rewards", 84_500.0, 1.5, now))
            db.execSQL(balSql, arrayOf(3L, "Amex Membership Rewards", 142_300.0, 1.5, now))

            // Seed a rotating-category window: Q2 2026 = 5% gas + streaming on
            // (hypothetical) Freedom-style card.
            val rotSql = """
                INSERT INTO rotating_categories
                  (cardId, category, multiplier, startEpochMillis, endEpochMillis, label)
                VALUES (?, ?, ?, ?, ?, ?)
            """.trimIndent()
            val q2Start = 1_743_465_600_000L // 2026-04-01 UTC
            val q2End = 1_751_414_399_000L   // 2026-06-30 23:59:59 UTC
            db.execSQL(rotSql, arrayOf(2L, "GAS", 5.0, q2Start, q2End, "Q2 2026 — Gas & Streaming"))
        }
    }
}
